const USER_ROLES = Object.freeze({
  ADMIN: 'ADMIN',
  HOSPITAL: 'HOSPITAL',
  DONOR: 'DONOR',
  BLOOD_REQUESTER: 'BLOOD_REQUESTER',
});

const BLOOD_GROUPS = Object.freeze(['A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-']);

const REQUEST_STATUS = Object.freeze({
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
});

const REQUEST_URGENCY = Object.freeze({
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  CRITICAL: 'CRITICAL',
});

const NOTIFICATION_TYPE = Object.freeze({
  INFO: 'INFO',
  SUCCESS: 'SUCCESS',
  WARNING: 'WARNING',
  ERROR: 'ERROR',
  ACTION_REQUIRED: 'ACTION_REQUIRED',
});

const AUDIT_ACTIONS = Object.freeze({
  CREATE: 'CREATE',
  UPDATE: 'UPDATE',
  DELETE: 'DELETE',
  APPROVE_DONATION: 'APPROVE_DONATION',
  REJECT_DONATION: 'REJECT_DONATION',
  APPROVE_BLOOD_REQUEST: 'APPROVE_BLOOD_REQUEST',
  REJECT_BLOOD_REQUEST: 'REJECT_BLOOD_REQUEST',
  INVENTORY_IN: 'INVENTORY_IN',
  INVENTORY_OUT: 'INVENTORY_OUT',
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
});

module.exports = {
  USER_ROLES,
  BLOOD_GROUPS,
  REQUEST_STATUS,
  REQUEST_URGENCY,
  NOTIFICATION_TYPE,
  AUDIT_ACTIONS,
};
